maintenance:
  - /.github
template/API:
  - Source/ApiTemplate
template/GraphQL:
  - Source/GraphQLTemplate
template/NuGet:
  - Source/NuGetTemplate
template/Orleans:
  - Source/OrleansTemplate
template/Item:
  - Source/EditorconfigTemplate
  - Source/GitattributesTemplate
